import { STAGES, id, now, type OfficeStore, type OfficeRuntime, type Project, type Task, type TaskStatus, type Stage } from '@autodev/shared';
export function validateDAG(tasks:Task[]):void {
 const map=new Map(tasks.map(t=>[t.id,t])); if(map.size!==tasks.length) throw new Error('Duplicate task ID');
 const visiting=new Set<string>(),done=new Set<string>();
 function visit(t:Task):void {if(visiting.has(t.id))throw new Error('DAG cycle');if(done.has(t.id))return;if(!t.assignee_agent||!t.definition_of_done.length)throw new Error('Task missing owner or DoD');visiting.add(t.id);for(const dep of t.depends_on){const parent=map.get(dep);if(!parent)throw new Error('Missing dependency '+dep);visit(parent);}visiting.delete(t.id);done.add(t.id);}
 for(const task of tasks)visit(task);
}
const transitions:Partial<Record<TaskStatus,TaskStatus[]>>={PENDING:['READY','SKIPPED'],READY:['QUEUED','RUNNING','SKIPPED'],QUEUED:['RUNNING','STALLED'],RUNNING:['VALIDATING','RETRYING','STALLED','BLOCKED','FAILED'],VALIDATING:['DONE','RETRYING','FAILED','BLOCKED'],RETRYING:['QUEUED','RUNNING','ESCALATED'],STALLED:['QUEUED','RUNNING','ESCALATED'],ESCALATED:['QUEUED','FAILED'],BLOCKED:['READY','FAILED'],FAILED:['READY'],DONE:['READY'],SKIPPED:['READY']};
export function assertTransition(from:TaskStatus,to:TaskStatus):void {if(!transitions[from]?.includes(to))throw new Error(`Invalid task transition ${from} -> ${to}`);}
export function retryDelay(attempt:number,transient=true,random=Math.random):number {return (transient?1000:250)*2**Math.min(attempt,8)+Math.floor(random()*500);}
const owners:Record<Stage,string[]>={INTAKE:['cs_agent'],DISCOVERY:['compliance_agent','ba_agent'],REQUIREMENTS:['ba_agent','po_agent'],PROPOSAL:['estimator_agent'],PLANNING:['pm_agent'],DESIGN_ARCH:['designer_agent','architect_agent'],DEVELOPMENT:['backend_dev','frontend_dev','tech_lead'],QA:['qa_agent'],SECURITY:['security_agent'],DEPLOY_UAT:['devops_agent','qa_agent'],RELEASING:['writer_agent','release_agent'],POST_DELIVERY:['account_agent']};
export function stageTasks(project:Project,stage:Stage,previous:string[]=[],revision=0):Task[]{
 const assigned=[...owners[stage]];if(stage==='DEVELOPMENT'){const request=JSON.stringify(project.brief_json);if(/mobile|pwa|android|ios/i.test(request))assigned.splice(2,0,'mobile_dev');if(/machine learning|pipeline data|data engineer|\bAI\b/i.test(request))assigned.splice(2,0,'data_agent');}
 const tasks=assigned.map((owner):Task=>({id:`${project.id}:${stage}:${owner}:${revision}`,project_id:project.id,stage,title:`${stage} — ${owner}`,description:`Kerjakan ${stage} sesuai brief dan acceptance criteria.`,assignee_agent:owner,depends_on:stage==='DEVELOPMENT'&&owner==='tech_lead'?[]:previous,priority:project.priority,story_refs:[],inputs_json:{revision},definition_of_done:['Output tervalidasi','Bukti terukur tersimpan'],validators:['schema','dod','security','traceability'],status:'PENDING',attempt:0,max_attempts:Number(project.config_json?.max_attempts??3),timeout_s:Number(project.config_json?.timeout_s??900),idempotency_key:`${project.id}:${stage}:${owner}:${revision}`,estimate_min:5,cost:{tokens_in:0,tokens_out:0,usd:0},created_at:now()}));
 if(stage==='DEVELOPMENT')tasks.find(t=>t.assignee_agent==='tech_lead')!.depends_on=tasks.filter(t=>t.assignee_agent!=='tech_lead').map(t=>t.id);
 if(stage==='REQUIREMENTS'||stage==='RELEASING'||stage==='DEPLOY_UAT')for(let i=1;i<tasks.length;i++)tasks[i]!.depends_on=[tasks[i-1]!.id];
 return tasks;
}
export function createOfficeEngine({store,runtime,concurrency=4,agentConcurrency=2,clock=()=>Date.now()}:{store:OfficeStore;runtime:OfficeRuntime;concurrency?:number;agentConcurrency?:number;clock?:()=>number}) {
 let timer:NodeJS.Timeout|undefined,busy=false; const running=new Map<string,{agent:string;controller:AbortController}>();
 async function event(project_id:string,type:string,payload:Record<string,unknown>,actor='orchestrator'){await store.emit({id:id('evt'),ts:now(),project_id,type,actor,payload});}
 async function change(task:Task,status:TaskStatus,patch:Partial<Task>={}){assertTransition(task.status,status);await store.updateTask(task.id,{...patch,status});await event(task.project_id,'task.status_changed',{task_id:task.id,from:task.status,to:status},task.assignee_agent);task.status=status;}
 async function seed(project:Project,stage:Stage,previous:string[]=[],revision=0){const tasks=stageTasks(project,stage,previous,revision);validateDAG([...await store.listTasks(project.id),...tasks]);for(const task of tasks){await store.putTask(task);await event(project.id,'task.created',{task});}}
 async function fail(project:Project,reason:string,task?:Task){if(task&&runtime.compensate)await runtime.compensate(project,task).catch(()=>undefined);await store.updateProject(project.id,{status:'FAILED',failure_reason:reason});await event(project.id,'system.error',{reason});}
 async function gate(project:Project):Promise<boolean>{const required=project.autonomy_mode==='FULL_MANUAL_REVIEW'||(project.autonomy_mode==='GATED_PROPOSAL'&&project.stage==='PROPOSAL')||(project.autonomy_mode==='GATED_RELEASE'&&project.stage==='SECURITY');if(!required)return true;let approval=await store.getApproval(project.id,project.stage);if(!approval){approval={id:id('apr'),project_id:project.id,gate:project.stage,requested_at:now(),timeout_at:new Date(clock()+Number(project.config_json?.gate_timeout_s??3600)*1000).toISOString(),default_action:(project.config_json?.gate_default_action as 'approve'|'reject'|'escalate')??'escalate'};await store.putApproval(approval);await store.updateProject(project.id,{status:'WAITING_APPROVAL'});await event(project.id,'gate.waiting',{approval});return false;}if(!approval.decision&&Date.parse(approval.timeout_at)<=clock()){approval.decision=approval.default_action;approval.decided_by='timeout';await store.putApproval(approval);await event(project.id,'gate.resolved',{approval});}if(approval.decision==='reject'){await store.updateProject(project.id,{status:'REJECTED'});return false;}if(approval.decision!=='approve')return false;await store.updateProject(project.id,{status:project.stage});return true;}
 async function execute(project:Project,task:Task){const controller=new AbortController();running.set(task.id,{agent:task.assignee_agent,controller});const timeout=setTimeout(()=>controller.abort(new Error('Task timeout')),task.timeout_s*1000);const heartbeat=setInterval(()=>store.updateTask(task.id,{heartbeat_at:now(),lease_until:new Date(clock()+60000).toISOString()}).catch(()=>undefined),10000);try{
 const result=await runtime.execute(project,task,{signal:controller.signal,heartbeat:()=>store.updateTask(task.id,{heartbeat_at:now(),lease_until:new Date(clock()+60000).toISOString()}),emit:(type,payload)=>event(project.id,type,payload,task.assignee_agent)});
 if(controller.signal.aborted)throw new Error('Task timeout');await change(task,'VALIDATING');if(!result.output||typeof result.output.summary!=='string')throw new Error('Invalid output: missing summary');
 if(result.output.status==='REJECTED'){await store.updateProject(project.id,{status:'REJECTED',failure_reason:result.output.summary});await change(task,'DONE',{output_json:result.output,finished_at:now()});return;}
 if(result.output.status==='BLOCKED'){await change(task,'BLOCKED',{output_json:result.output});await store.updateProject(project.id,{status:'PAUSED',failure_reason:result.output.summary});return;}
 const current=await store.getProject(project.id),cost=result.cost??{tokens_in:0,tokens_out:0,usd:0};await store.updateProject(project.id,{...result.project_patch,...(result.cost_accounted?{}:{cost_usd:Number(current.cost_usd)+cost.usd,tokens_total:Number(current.tokens_total)+cost.tokens_in+cost.tokens_out})});await change(task,'DONE',{output_json:result.output,cost,finished_at:now(),lease_until:null});
 }catch(error){const message=error instanceof Error?error.message:String(error);const current=await store.getProject(project.id);if(current.status==='CANCELLED'){await store.updateTask(task.id,{status:'FAILED',error_json:{message:'Cancelled'}});return;}
 const attempt=task.attempt;if(attempt>=task.max_attempts){await change(task,'RETRYING',{error_json:{message}});await change(task,'ESCALATED');const replans=Number(current.replans??0);if(replans<Number(current.config_json?.max_replans??2)){await store.updateProject(project.id,{replans:replans+1});await change(task,'QUEUED',{max_attempts:task.max_attempts+1,retry_at:new Date(clock()+retryDelay(attempt)).toISOString(),inputs_json:{...task.inputs_json,feedback:message,replan:replans+1}});await event(project.id,'agent.message',{from:'pm_agent',to:task.assignee_agent,summary:'Replan dengan feedback',feedback:message});}else{await change(task,'FAILED');await store.putRecord('dead_letters',{id:id('dlq'),project_id:project.id,task_id:task.id,reason:message});await fail(current,message,task);}}
 else await change(task,'RETRYING',{error_json:{message},retry_at:new Date(clock()+retryDelay(attempt,/rate|network|timeout|429|503/i.test(message))).toISOString(),inputs_json:{...task.inputs_json,feedback:message}});
 }finally{clearTimeout(timeout);clearInterval(heartbeat);running.delete(task.id);}}
 async function tick(){if(busy)return;busy=true;try{const projects=(await store.listProjects()).sort((a,b)=>(b.priority-a.priority)||(Date.parse(a.deadline??'9999-01-01')-Date.parse(b.deadline??'9999-01-01')));for(const project of projects){if(['PAUSED','CANCELLED','FAILED','REJECTED','DELIVERED'].includes(project.status)){if(project.status==='CANCELLED')for(const [taskId,entry] of running)if(taskId.startsWith(project.id+':'))entry.controller.abort();continue;}
 const ratio=Number(project.cost_usd)/Number(project.budget_cap_usd);if(ratio>=1||project.tokens_total>=Number(project.token_cap??Infinity)){await store.updateProject(project.id,{status:'PAUSED',failure_reason:'Budget exceeded'});await event(project.id,'budget.exceeded',{cost_usd:project.cost_usd});continue;}for(const threshold of [.7,.9])if(ratio>=threshold&&!project[`budget_warn_${threshold}`]){await event(project.id,'budget.warning',{threshold});await store.updateProject(project.id,{[`budget_warn_${threshold}`]:true});}
 let tasks=await store.listTasks(project.id);if(!tasks.length){await store.updateProject(project.id,{status:project.stage,started_at:project.started_at??now()});await seed(project,project.stage);tasks=await store.listTasks(project.id);}validateDAG(tasks);
 for(const task of tasks){if(['RUNNING','VALIDATING'].includes(task.status)&&!running.has(task.id)&&Date.parse(task.lease_until??task.heartbeat_at??task.started_at??'1970-01-01')<clock()){await store.updateTask(task.id,{status:'STALLED',retry_at:now()});task.status='STALLED';await event(project.id,'task.status_changed',{task_id:task.id,to:'STALLED'});}}
 if(!tasks.some(t=>t.stage===project.stage&&!t.inputs_json.superseded)){const previous=tasks.filter(t=>t.stage===STAGES[STAGES.indexOf(project.stage)-1]&&t.status==='DONE'&&!t.inputs_json.superseded).map(t=>t.id);await seed(project,project.stage,previous,Number(project.qa_cycles??0));continue;}
 const current=tasks.filter(t=>t.stage===project.stage&&!t.inputs_json.superseded);if(current.length&&current.every(t=>t.status==='DONE'||t.status==='SKIPPED')){if(!await gate(project))continue;const failed=current.find(t=>t.output_json?.quality_pass===false);if(failed&&['QA','SECURITY','DEPLOY_UAT'].includes(project.stage)){const cycles=Number(project.qa_cycles??0)+1;if(cycles>Number(project.config_json?.max_qa_cycles??3)){await fail(project,'Quality repair cycles exhausted',failed);continue;}if(runtime.compensate)await runtime.compensate(project,failed);for(const t of tasks.filter(t=>['DEVELOPMENT','QA','SECURITY','DEPLOY_UAT'].includes(t.stage)))await store.updateTask(t.id,{inputs_json:{...t.inputs_json,superseded:true}});await store.updateProject(project.id,{stage:'DEVELOPMENT',status:'DEVELOPMENT',qa_cycles:cycles,repair_feedback:failed.output_json});await seed(project,'DEVELOPMENT',[],cycles);await event(project.id,'project.stage_changed',{from:project.stage,to:'DEVELOPMENT',repair:true});continue;}
 const next=STAGES[STAGES.indexOf(project.stage)+1];if(!next){await store.updateProject(project.id,{status:'DELIVERED',delivered_at:now()});continue;}if(next==='POST_DELIVERY'){const quality=await store.listRecords('test_runs',project.id),security=await store.listRecords('security_reports',project.id),deploys=await store.listRecords('deployments',project.id),emails=await store.listRecords('emails',project.id),artifacts=await store.listRecords('artifacts',project.id),bugs=await store.listRecords('bugs',project.id);const latestUnit=quality.filter(r=>r.kind==='unit-integration').at(-1),latestE2e=quality.filter(r=>r.kind==='e2e').at(-1),latestSecurity=security.at(-1),latestDeploy=deploys.at(-1);if(!latestUnit||Number(latestUnit.failed)!==0||Number(latestUnit.coverage)<Number(project.config_json?.coverage_threshold??70)||!latestE2e||Number(latestE2e.failed)!==0||Number(latestE2e.passed)<1||!latestSecurity||Number(latestSecurity.high)!==0||Number(latestSecurity.critical)!==0||latestDeploy?.status!=='healthy'||bugs.some(b=>['P0','P1'].includes(String(b.severity))&&b.status!=='fixed')||!emails.some(r=>['sent','delivered'].includes(String(r.status)))||!artifacts.some(r=>r.type==='HandoverPack')){await fail(project,'Delivery evidence incomplete');continue;}}
 await store.updateProject(project.id,{stage:next,status:next});await seed(project,next,current.map(t=>t.id),Number(project.qa_cycles??0));await event(project.id,'project.stage_changed',{from:project.stage,to:next});continue;}
 if(project.status==='WAITING_APPROVAL')continue;const done=new Set(tasks.filter(t=>t.status==='DONE'||t.status==='SKIPPED').map(t=>t.id));for(const task of current.sort((a,b)=>b.priority-a.priority)){if(running.size>=concurrency)break;if(task.status==='PENDING'&&task.depends_on.every(dep=>done.has(dep)))await change(task,'READY');if(!['READY','QUEUED','RETRYING','STALLED'].includes(task.status)||Date.parse(task.retry_at??'1970-01-01')>clock())continue;if([...running.values()].filter(r=>r.agent===task.assignee_agent).length>=agentConcurrency)continue;if(task.status!=='QUEUED')await change(task,'QUEUED');if(await store.claimTask(task.id,new Date(clock()+60000).toISOString())){task.status='RUNNING';task.attempt++;await event(project.id,'task.status_changed',{task_id:task.id,to:'RUNNING'},task.assignee_agent);void execute(project,task);}}
 }}finally{busy=false;}}
 return {tick,start(){if(!timer){timer=setInterval(()=>void tick().catch(error=>console.error(JSON.stringify({type:'system.error',error:String(error)}))),500);void tick();}},async stop(){clearInterval(timer);timer=undefined;while(running.size){const {promise,resolve}=Promise.withResolvers<void>();setTimeout(resolve,20);await promise;}},async replan(projectId:string,newTasks:Task[]){const existing=await store.listTasks(projectId);validateDAG([...existing,...newTasks]);for(const task of newTasks)await store.putTask(task);}};
}
