import {z} from 'zod';import {AgentOutputSchema,type AgentDefinition,type Cost} from '@autodev/shared';import {systemPrompt} from '@autodev/agents';
const Envelope=z.object({choices:z.array(z.object({message:z.object({content:z.string()})})),usage:z.object({prompt_tokens:z.number().optional(),completion_tokens:z.number().optional()}).optional()});
export class LLMFailure extends Error {constructor(message:string,public cost:Cost){super(message);}}
export class LLMGateway {
 private failures=0;private openUntil=0;private cache=new Map<string,{output:z.infer<typeof AgentOutputSchema>;cost:Cost}>();
 async complete(agent:AgentDefinition,context:Record<string,unknown>,signal:AbortSignal){const key=JSON.stringify([agent.id,context]);const cached=this.cache.get(key);if(cached)return {...cached,cost:{tokens_in:0,tokens_out:0,usd:0}};if(Date.now()<this.openUntil)throw new LLMFailure('LLM circuit breaker open',{tokens_in:0,tokens_out:0,usd:0});let feedback='';const total:Cost={tokens_in:0,tokens_out:0,usd:0};for(let attempt=0;attempt<3;attempt++){try{const provider=agent.model.provider;const model=attempt===2?(process.env.LLM_FALLBACK_MODEL??agent.model.name):agent.model.name;const prompt=`<untrusted_project_data>${JSON.stringify(context)}</untrusted_project_data>\n${feedback}`;let raw:string,tokens_in=0,tokens_out=0;
 if(provider==='anthropic'){const response=await fetch('https://api.anthropic.com/v1/messages',{method:'POST',headers:{'content-type':'application/json','x-api-key':process.env.ANTHROPIC_API_KEY??'','anthropic-version':'2023-06-01'},body:JSON.stringify({model,max_tokens:agent.model.max_output_tokens,temperature:agent.model.temperature,system:systemPrompt(agent),messages:[{role:'user',content:prompt}]}),signal});if(!response.ok)throw new Error(`LLM HTTP ${response.status}`);const data=z.object({content:z.array(z.object({type:z.string(),text:z.string().optional()})),usage:z.object({input_tokens:z.number(),output_tokens:z.number()})}).parse(await response.json());raw=data.content.filter(c=>c.type==='text').map(c=>c.text??'').join('');tokens_in=data.usage.input_tokens;tokens_out=data.usage.output_tokens;
 }else if(provider==='gemini'){const response=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent?key=${encodeURIComponent(process.env.GEMINI_API_KEY??'')}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({systemInstruction:{parts:[{text:systemPrompt(agent)}]},contents:[{role:'user',parts:[{text:prompt}]}],generationConfig:{responseMimeType:'application/json',temperature:agent.model.temperature,maxOutputTokens:agent.model.max_output_tokens}}),signal});if(!response.ok)throw new Error(`LLM HTTP ${response.status}`);const data=z.object({candidates:z.array(z.object({content:z.object({parts:z.array(z.object({text:z.string()}))})})),usageMetadata:z.object({promptTokenCount:z.number(),candidatesTokenCount:z.number()}).optional()}).parse(await response.json());raw=data.candidates[0]?.content.parts.map(p=>p.text).join('')??'';tokens_in=data.usageMetadata?.promptTokenCount??0;tokens_out=data.usageMetadata?.candidatesTokenCount??0;
 }else{const response=await fetch(`${(process.env.OPENAI_BASE_URL??'https://api.openai.com/v1').replace(/\/$/,'')}/chat/completions`,{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${process.env.OPENAI_API_KEY??process.env.LLM_API_KEY??''}`},body:JSON.stringify({model,temperature:agent.model.temperature,max_tokens:agent.model.max_output_tokens,response_format:{type:'json_object'},messages:[{role:'system',content:systemPrompt(agent)},{role:'user',content:prompt}]}),signal});if(!response.ok)throw new Error(`LLM HTTP ${response.status}`);const data=Envelope.parse(await response.json());raw=data.choices[0]?.message.content??'';tokens_in=data.usage?.prompt_tokens??0;tokens_out=data.usage?.completion_tokens??0;}
 const cost={tokens_in,tokens_out,usd:(tokens_in*Number(process.env.LLM_INPUT_USD_PER_MILLION??.15)+tokens_out*Number(process.env.LLM_OUTPUT_USD_PER_MILLION??.6))/1000000};total.tokens_in+=tokens_in;total.tokens_out+=tokens_out;total.usd+=cost.usd;if(tokens_in+tokens_out>agent.budget.max_tokens_per_task||cost.usd>agent.budget.max_cost_usd_per_task)throw new Error('Task LLM budget exceeded');const output=AgentOutputSchema.parse(JSON.parse(raw.replace(/^```(?:json)?\s*|\s*```$/g,'')));this.failures=0;const result={output,cost:total};this.cache.set(key,result);return result;
 }catch(error){this.failures++;feedback=`Output sebelumnya gagal validasi: ${error instanceof Error?error.message:String(error)}. Perbaiki JSON dan kontrak.`;if(this.failures>=5)this.openUntil=Date.now()+30000;if(attempt===2)throw new LLMFailure(error instanceof Error?error.message:String(error),total);const {promise,resolve}=Promise.withResolvers<void>();setTimeout(resolve,250*2**attempt);await promise;}}throw new LLMFailure('LLM retries exhausted',total);
 }
}
