import http from 'node:http';
import {readFile,writeFile} from 'node:fs/promises';
import {randomUUID,timingSafeEqual} from 'node:crypto';
const configuration=JSON.parse(await readFile(new URL('./project.json',import.meta.url),'utf8'));
const products=configuration.products??[{id:'coffee',name:'Kopi Senja Arabika',price:45000},{id:'latte',name:'Kopi Susu',price:25000}];
let orders=[];try{orders=JSON.parse(await readFile('/tmp/orders.json','utf8'));}catch{}
let setupConsumed=false;try{setupConsumed=(await readFile('/tmp/setup-consumed','utf8'))==='true';}catch{}
const escape=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function calculateTotal(items){if(!Array.isArray(items)||!items.length||items.length>100)throw new Error('Keranjang tidak valid');return items.reduce((total,item)=>{const product=products.find(p=>p.id===item.id);if(!product||!Number.isInteger(item.quantity)||item.quantity<1||item.quantity>100)throw new Error('Produk/jumlah tidak valid');return total+product.price*item.quantity;},0);}
export const server=http.createServer(async(req,res)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('X-Frame-Options','DENY');res.setHeader('Referrer-Policy','no-referrer');res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; base-uri 'none'; frame-ancestors 'none'");const path=new URL(req.url,'http://localhost').pathname;try{
if(path==='/health'){res.setHeader('content-type','application/json');res.end(JSON.stringify({status:'ok',version:process.env.APP_VERSION??'1.0.0'}));return;}
if(path==='/setup'){res.setHeader('Cache-Control','no-store');const url=new URL(req.url,'http://localhost');let token=url.searchParams.get('token')??'';if(req.method==='POST'){let body='';for await(const chunk of req){body+=chunk;if(body.length>2000)throw new Error('Input too large');}token=new URLSearchParams(body).get('token')??'';}const expected=process.env.APP_SETUP_TOKEN??'';if(!expected||setupConsumed||Date.now()>Date.parse(process.env.APP_SETUP_EXPIRES_AT??'1970-01-01')||token.length!==expected.length||!timingSafeEqual(Buffer.from(token),Buffer.from(expected))){res.writeHead(403);res.end('Tautan setup tidak valid, telah dipakai, atau kedaluwarsa. Hubungi operator.');return;}if(req.method==='GET'){res.setHeader('content-type','text/html;charset=utf-8');res.end(`<!doctype html><html lang="id"><h1>Aktifkan akses admin</h1><form method="POST" action="./setup"><input type="hidden" name="token" value="${escape(token)}"><button>Aktifkan akses pada browser ini</button></form><p>Tautan sekali pakai, berlaku 15 menit. Jangan membagikan tautan.</p></html>`);return;}if(req.method!=='POST'){res.writeHead(405);res.end();return;}setupConsumed=true;await writeFile('/tmp/setup-consumed','true');res.setHeader('Set-Cookie',`app_admin=${process.env.APP_ADMIN_TOKEN}; HttpOnly; SameSite=Strict; Path=/live/${process.env.PROJECT_ID??''}/; Max-Age=3600${process.env.APP_HTTPS==='true'?'; Secure':''}`);res.writeHead(303,{Location:'./admin'});res.end();return;}
if(path==='/api/products'){res.setHeader('content-type','application/json');res.end(JSON.stringify(products));return;}
if(path==='/api/orders'&&req.method==='POST'){let body='';for await(const chunk of req){body+=chunk;if(body.length>16000){res.writeHead(413);res.end();return;}}const input=JSON.parse(body);const total=calculateTotal(input.items);if(typeof input.name!=='string'||input.name.length<2||input.name.length>100)throw new Error('Nama wajib');const order={id:randomUUID(),name:input.name,total,status:'menunggu_transfer',items:input.items};orders.push(order);await writeFile('/tmp/orders.json',JSON.stringify(orders));res.writeHead(201,{'content-type':'application/json'});res.end(JSON.stringify(order));return;}
if(path==='/api/admin/orders'){const cookie=req.headers.cookie?.split(';').map(v=>v.trim()).find(v=>v.startsWith('app_admin='))?.slice(10);const supplied=req.headers.authorization??(cookie?'Bearer '+cookie:'');const expected='Bearer '+(process.env.APP_ADMIN_TOKEN??'');if(!process.env.APP_ADMIN_TOKEN||supplied.length!==expected.length||!timingSafeEqual(Buffer.from(supplied),Buffer.from(expected))){res.writeHead(401);res.end('Unauthorized');return;}res.setHeader('content-type','application/json');res.end(JSON.stringify(orders));return;}
if(path==='/app.js'||path==='/style.css'){res.setHeader('content-type',path.endsWith('.js')?'text/javascript':'text/css');res.end(await readFile(new URL('.'+path,import.meta.url)));return;}
if(path!=='/'&&path!=='/admin'){res.writeHead(404);res.end('Tidak ditemukan');return;}
res.setHeader('content-type','text/html;charset=utf-8');res.end(`<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${escape(configuration.title)}</title><link rel="stylesheet" href="./style.css"></head><body><header><a href="./">${escape(configuration.title)}</a><nav><a href="#layanan">Layanan</a><a href="#tentang">Tentang</a><a href="#kontak">Kontak</a><a href="./admin">Admin</a></nav></header><main><section class="hero"><span>SELAMAT DATANG</span><h1>${escape(configuration.title)}</h1><p>${escape(configuration.goal)}</p><a class="button" href="#kontak">Hubungi Kami</a></section><section id="layanan"><h2>Layanan & Produk</h2><div class="grid">${products.map(p=>`<article><h3>${escape(p.name)}</h3><p>Rp ${p.price.toLocaleString('id-ID')}</p><button data-product="${escape(p.id)}">Tambahkan</button></article>`).join('')}</div></section><section id="tentang"><h2>Tentang Kami</h2><p>${escape(configuration.goal)}</p><ul>${configuration.features.map(f=>`<li>${escape(f)}</li>`).join('')}</ul></section><section id="kontak"><h2>Hubungi Kami</h2><p><a href="mailto:${escape(configuration.email)}">${escape(configuration.email)}</a></p><form id="checkout"><label>Nama <input name="name" required minlength="2"></label><button>Pesan / Konsultasi</button></form><p id="status" aria-live="polite"></p><p>Pembayaran transfer/QRIS sandbox: tidak memproses uang asli. Integrasi payment produksi membutuhkan kredensial klien.</p></section>${path==='/admin'?'<section><h2>Admin Pesanan</h2><label>Token admin <input type="password" id="token"></label><button id="load-orders">Lihat pesanan</button><pre id="orders"></pre><p>Token admin diberikan operator melalui saluran aman. Tidak ada password default.</p></section>':''}</main><footer>© ${new Date().getFullYear()} ${escape(configuration.title)}</footer><script src="./app.js" defer></script></body></html>`);
}catch(error){res.writeHead(400,{'content-type':'application/json'});res.end(JSON.stringify({error:error.message}));}});
if(process.env.NODE_ENV!=='test')server.listen(Number(process.env.PORT??8080),'0.0.0.0');
