import { z } from 'zod';
export const STAGES = ['INTAKE','DISCOVERY','REQUIREMENTS','PROPOSAL','PLANNING','DESIGN_ARCH','DEVELOPMENT','QA','SECURITY','DEPLOY_UAT','RELEASING','POST_DELIVERY'] as const;
export const AUTONOMY_MODES = ['FULL_AUTO','GATED_PROPOSAL','GATED_RELEASE','FULL_MANUAL_REVIEW'] as const;
export type Stage = typeof STAGES[number];
export type AutonomyMode = typeof AUTONOMY_MODES[number];
export const TASK_STATUSES = ['PENDING','READY','QUEUED','RUNNING','VALIDATING','DONE','RETRYING','ESCALATED','FAILED','BLOCKED','STALLED','SKIPPED'] as const;
export type TaskStatus = typeof TASK_STATUSES[number];
export interface Project { id:string; client_id?:string; title:string; brief_json:Record<string,unknown>; client_email?:string; status:string; stage:Stage; autonomy_mode:AutonomyMode; priority:number; deadline?:string|null; budget_cap_usd:number; cost_usd:number; tokens_total:number; token_cap?:number; repo_url?:string|null; live_url?:string|null; staging_url?:string|null; version?:string; started_at?:string|null; delivered_at?:string|null; created_at?:string; updated_at?:string; config_json?:Record<string,unknown>; [key:string]:unknown }
export interface Cost {tokens_in:number;tokens_out:number;usd:number}
export interface Task {id:string;project_id:string;stage:Stage;title:string;description:string;assignee_agent:string;depends_on:string[];priority:number;story_refs:string[];inputs_json:Record<string,unknown>;output_json?:Record<string,unknown>|null;definition_of_done:string[];validators:string[];status:TaskStatus;attempt:number;max_attempts:number;timeout_s:number;idempotency_key:string;estimate_min:number;cost:Cost;created_at:string;started_at?:string|null;finished_at?:string|null;heartbeat_at?:string|null;lease_until?:string|null;retry_at?:string|null;error_json?:Record<string,unknown>|null;[key:string]:unknown}
export interface OfficeEvent {id:string;ts:string;project_id:string;type:string;actor:string;payload:Record<string,unknown>}
export interface Artifact {id:string;project_id:string;type:string;name:string;version:number;storage_path:string;mime:string;size:number;checksum:string;created_by:string;meta_json:Record<string,unknown>;created_at:string}
export interface AgentDefinition {id:string;display_name:string;role:string;avatar:string;prompt?:string;model:{provider:string;name:string;temperature:number;max_output_tokens:number};budget:{max_tokens_per_task:number;max_cost_usd_per_task:number;max_retries:number;timeout_seconds:number};tools:string[];system_prompt_file:string;output_schema:string;definition_of_done:string[];handoff_to:string[];status?:string}
export interface Approval {id:string;project_id:string;gate:string;requested_at:string;timeout_at:string;decision?:'approve'|'reject'|'escalate'|null;decided_by?:string;reason?:string;default_action:'approve'|'reject'|'escalate'}
export interface OfficeStore {listProjects():Promise<Project[]>;getProject(id:string):Promise<Project>;updateProject(id:string,patch:Partial<Project>):Promise<void>;listTasks(projectId:string):Promise<Task[]>;putTask(task:Task):Promise<void>;claimTask(id:string,leaseUntil:string):Promise<boolean>;updateTask(id:string,patch:Partial<Task>):Promise<void>;emit(event:OfficeEvent):Promise<void>;putRecord(table:string,record:Record<string,unknown>):Promise<void>;listRecords(table:string,projectId:string):Promise<Record<string,unknown>[]>;getApproval(projectId:string,gate:string):Promise<Approval|undefined>;putApproval(approval:Approval):Promise<void>;reserveBudget(projectId:string,usd:number,tokens:number):Promise<boolean>;settleBudget(projectId:string,reservedUsd:number,reservedTokens:number,cost:Cost):Promise<void>}
export interface ExecutionContext {heartbeat():Promise<void>;emit(type:string,payload:Record<string,unknown>):Promise<void>;signal:AbortSignal}
export interface ExecutionResult {output:Record<string,unknown>;cost?:Cost;cost_accounted?:boolean;project_patch?:Partial<Project>}
export interface OfficeRuntime {execute(project:Project,task:Task,context:ExecutionContext):Promise<ExecutionResult>;compensate?(project:Project,task:Task):Promise<void>}
export const ProjectBriefSchema = z.object({goal:z.string().min(5),features:z.array(z.string().min(2)).min(3),email:z.string().email(),platform:z.string().default('web'),locale:z.string().default('id'),assumptions:z.array(z.string()).default([])}).passthrough();
export const CreateProjectSchema = z.object({title:z.string().min(3).max(200),brief_json:z.record(z.unknown()),client_email:z.string().email(),autonomy_mode:z.enum(AUTONOMY_MODES).default('FULL_AUTO'),budget_cap_usd:z.number().positive().default(25),priority:z.number().int().min(0).max(100).default(50)});
export const AgentOutputSchema = z.object({status:z.enum(['DONE','BLOCKED','REJECTED']),summary:z.string().min(1),assumptions:z.array(z.string()).default([]),artifacts:z.array(z.object({name:z.string(),type:z.string(),content:z.string()})).default([]),data:z.record(z.unknown()).default({}),files:z.array(z.object({path:z.string(),content:z.string()})).default([]),tool_calls:z.array(z.object({name:z.string(),input:z.record(z.unknown())})).default([])});
export const id = (prefix:string) => `${prefix}_${crypto.randomUUID()}`;
export const now = () => new Date().toISOString();
