import { randomBytes, scryptSync, timingSafeEqual, createHash, createHmac, createCipheriv, createDecipheriv } from 'node:crypto';
import { z } from 'zod';
import { pool } from './store.js';
export const secret=process.env.SESSION_SECRET??'development-only-change-this-secret-2026';
export function passwordHash(password:string) {const salt=randomBytes(16).toString('hex');return `${salt}:${scryptSync(password,salt,64).toString('hex')}`;}
export function verifyPassword(password:string,hash:string) {const [salt,key]=hash.split(':');if(!salt||!key)return false;const actual=scryptSync(password,salt,64),expected=Buffer.from(key,'hex');return actual.length===expected.length&&timingSafeEqual(actual,expected);}
export function digest(value:string) {return createHash('sha256').update(value).digest('hex');}
export function portalToken(projectId:string,ttl=14*86400) {const data=Buffer.from(JSON.stringify({project_id:projectId,exp:Math.floor(Date.now()/1000)+ttl})).toString('base64url');return `${data}.${createHmac('sha256',secret).update(data).digest('base64url')}`;}
export function verifyPortal(token:string):string {const [data,sig,...rest]=token.split('.');if(!data||!sig||rest.length)throw Object.assign(new Error('Invalid portal token'),{statusCode:401});const expected=Buffer.from(createHmac('sha256',secret).update(data).digest('base64url'));const actual=Buffer.from(sig);if(actual.length!==expected.length||!timingSafeEqual(actual,expected))throw Object.assign(new Error('Invalid portal token'),{statusCode:401});const payload=z.object({project_id:z.string().min(1),exp:z.number().int()}).parse(JSON.parse(Buffer.from(data,'base64url').toString()));if(payload.exp<=Date.now()/1000)throw Object.assign(new Error('Expired portal token'),{statusCode:401});return payload.project_id;}
export function encrypt(value:unknown) {const iv=randomBytes(12),key=createHash('sha256').update(process.env.SETTINGS_KEY||secret).digest(),cipher=createCipheriv('aes-256-gcm',key,iv);const data=Buffer.concat([cipher.update(JSON.stringify(value)),cipher.final()]);return Buffer.concat([iv,cipher.getAuthTag(),data]).toString('base64');}
export function decrypt(value:string):unknown {const b=Buffer.from(value,'base64'),cipher=createDecipheriv('aes-256-gcm',createHash('sha256').update(process.env.SETTINGS_KEY||secret).digest(),b.subarray(0,12));cipher.setAuthTag(b.subarray(12,28));return JSON.parse(Buffer.concat([cipher.update(b.subarray(28)),cipher.final()]).toString());}
export async function sessionUser(token?:string) {if(!token)return undefined;const row=(await pool.query('SELECT u.id,u.email,u.name,u.role,s.csrf_token FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=$1 AND s.expires_at>now()',[digest(token)])).rows[0];return row?z.object({id:z.string(),email:z.string(),name:z.string(),role:z.enum(['Admin','Operator','Viewer','Client']),csrf_token:z.string()}).parse(row):undefined;}
