import pg from 'pg';
import { randomUUID } from 'node:crypto';
import { z } from 'zod';
import type { Project, Task, OfficeEvent, Approval } from '@autodev/shared';
import { STAGES,AUTONOMY_MODES,TASK_STATUSES } from '@autodev/shared';
const projectSchema=z.object({id:z.string(),client_id:z.string().optional(),title:z.string(),brief_json:z.record(z.unknown()),client_email:z.string().optional(),status:z.string(),stage:z.enum(STAGES),autonomy_mode:z.enum(AUTONOMY_MODES),priority:z.number(),deadline:z.string().nullable().optional(),budget_cap_usd:z.number(),cost_usd:z.number(),tokens_total:z.number(),token_cap:z.number().optional(),repo_url:z.string().nullable().optional(),live_url:z.string().nullable().optional(),staging_url:z.string().nullable().optional(),version:z.string().optional(),started_at:z.string().nullable().optional(),delivered_at:z.string().nullable().optional(),created_at:z.string().optional(),updated_at:z.string().optional(),config_json:z.record(z.unknown()).optional()}).passthrough();
const taskSchema=z.object({id:z.string(),project_id:z.string(),stage:z.enum(STAGES),title:z.string(),description:z.string(),assignee_agent:z.string(),depends_on:z.array(z.string()),priority:z.number(),story_refs:z.array(z.string()),inputs_json:z.record(z.unknown()),output_json:z.record(z.unknown()).nullable().optional(),definition_of_done:z.array(z.string()),validators:z.array(z.string()),status:z.enum(TASK_STATUSES),attempt:z.number(),max_attempts:z.number(),timeout_s:z.number(),idempotency_key:z.string(),estimate_min:z.number(),cost:z.object({tokens_in:z.number(),tokens_out:z.number(),usd:z.number()}),created_at:z.string(),started_at:z.string().nullable().optional(),finished_at:z.string().nullable().optional(),heartbeat_at:z.string().nullable().optional(),lease_until:z.string().nullable().optional(),retry_at:z.string().nullable().optional(),error_json:z.record(z.unknown()).nullable().optional()}).passthrough();
export const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL ?? 'postgres://autodev:autodev@localhost:5432/autodev', max: 12 });
export const tables:Record<string,true> = {clients:true,projects:true,stages:true,tasks:true,task_dependencies:true,agents:true,agent_messages:true,tool_calls:true,artifacts:true,requirements:true,test_runs:true,bugs:true,deployments:true,emails:true,approvals:true,usage_costs:true,events:true,chat_sessions:true,chat_messages:true,knowledge_items:true,surveys:true,change_requests:true,security_reports:true,dead_letters:true};
function table(name:string) { if (!Object.hasOwn(tables,name)) throw new Error('Unknown record table'); return name; }
export class PostgresStore {
 async putRecord(name:string, record:Record<string,unknown>):Promise<void> {
  const id = String(record.id ?? randomUUID()); const data = {...record,id};
  await pool.query(`INSERT INTO ${table(name)}(id,project_id,data) VALUES($1,$2,$3) ${name === 'events' ? 'ON CONFLICT(id) DO NOTHING' : 'ON CONFLICT(id) DO UPDATE SET data=EXCLUDED.data,project_id=EXCLUDED.project_id,updated_at=now()'}`, [id, record.project_id ?? (name === 'projects' ? id : null), JSON.stringify(data)]);
 }
 async listRecords(name:string,projectId?:string):Promise<Record<string,unknown>[]> { const q=await pool.query(`SELECT data FROM ${table(name)} ${projectId ? 'WHERE project_id=$1' : ''} ORDER BY created_at,id`,projectId?[projectId]:[]);return q.rows.map(r=>z.record(z.unknown()).parse(r.data)); }
 async getRecord(name:string,id:string):Promise<Record<string,unknown>|undefined> { const data=(await pool.query(`SELECT data FROM ${table(name)} WHERE id=$1`,[id])).rows[0]?.data;return data?z.record(z.unknown()).parse(data):undefined; }
 async patchRecord(name:string,id:string,patch:Record<string,unknown>):Promise<void> { try{const q=await pool.query(`UPDATE ${table(name)} SET data=data || $2::jsonb,updated_at=now() WHERE id=$1`,[id,JSON.stringify(patch)]);if(!q.rowCount) throw Object.assign(new Error('Record not found'),{statusCode:404});}catch(error){if(error instanceof Error&&error.message==='Approval already decided')throw Object.assign(error,{statusCode:409});throw error;} }
 async listProjects():Promise<Project[]> { return (await this.listRecords('projects')).map(p=>projectSchema.parse(p)); }
 async getProject(id:string):Promise<Project> { const p=await this.getRecord('projects',id);if(!p) throw Object.assign(new Error('Project not found'),{statusCode:404}); return projectSchema.parse(p); }
 async updateProject(id:string,patch:Partial<Project>):Promise<void> { await this.patchRecord('projects',id,patch as Record<string,unknown>); }
 async listTasks(projectId:string):Promise<Task[]> { return (await this.listRecords('tasks',projectId)).map(t=>taskSchema.parse(t)); }
 async putTask(task:Task):Promise<void> { await this.putRecord('tasks',task as unknown as Record<string,unknown>); for(const dep of task.depends_on) await this.putRecord('task_dependencies',{id:`${task.id}:${dep}`,project_id:task.project_id,task_id:task.id,depends_on_task_id:dep}); }
 async claimTask(id:string,leaseUntil:string):Promise<boolean> { const q=await pool.query(`UPDATE tasks SET data=data || jsonb_build_object('status','RUNNING','attempt',COALESCE((data->>'attempt')::int,0)+1,'lease_until',$2::text,'heartbeat_at',now()::text,'started_at',now()::text),updated_at=now() WHERE id=$1 AND data->>'status' IN ('PENDING','READY','QUEUED','RETRYING','STALLED') RETURNING id`,[id,leaseUntil]);return Boolean(q.rowCount); }
 async updateTask(id:string,patch:Partial<Task>):Promise<void> { await this.patchRecord('tasks',id,patch as Record<string,unknown>); }
 async emit(event:OfficeEvent):Promise<void> { await this.putRecord('events',{...event});if(event.type==='agent.message')await this.putRecord('agent_messages',{id:event.id,project_id:event.project_id,task_id:event.payload.task_id,from_agent:event.payload.from??event.actor,to_agent:event.payload.to,kind:'handoff',content:event.payload.content??event.payload.summary,payload:event.payload,ts:event.ts});if(event.type==='agent.tool_call')await this.putRecord('tool_calls',{id:event.id,project_id:event.project_id,task_id:event.payload.task_id,agent_id:event.actor,tool:event.payload.tool,input_json:event.payload.input,output_json:event.payload.output,status:event.payload.status??'recorded',duration_ms:event.payload.duration_ms,ts:event.ts});if(event.type==='project.created')await this.putRecord('stages',{id:`${event.project_id}:INTAKE`,project_id:event.project_id,name:'INTAKE',status:'RUNNING',started_at:event.ts});if(event.type==='project.stage_changed'){const from=String(event.payload.from),to=String(event.payload.to);if(await this.getRecord('stages',`${event.project_id}:${from}`))await this.patchRecord('stages',`${event.project_id}:${from}`,{status:'DONE',ended_at:event.ts});await this.putRecord('stages',{id:`${event.project_id}:${to}`,project_id:event.project_id,name:to,status:'RUNNING',started_at:event.ts});}await pool.query("SELECT pg_notify('office_events',$1)",[JSON.stringify({id:event.id})]); }
 async getApproval(projectId:string,gate:string):Promise<Approval|undefined> { const q=await pool.query("SELECT data FROM approvals WHERE project_id=$1 AND data->>'gate'=$2 ORDER BY created_at DESC LIMIT 1",[projectId,gate]);const data=q.rows[0]?.data;return data?z.object({id:z.string(),project_id:z.string(),gate:z.string(),requested_at:z.string(),timeout_at:z.string(),decision:z.enum(['approve','reject','escalate']).nullable().optional(),decided_by:z.string().optional(),reason:z.string().optional(),default_action:z.enum(['approve','reject','escalate'])}).parse(data):undefined; }
 async putApproval(approval:Approval):Promise<void> {await this.putRecord('approvals',approval as unknown as Record<string,unknown>);}
 async reserveBudget(projectId:string,usd:number,tokens:number):Promise<boolean> {z.number().nonnegative().finite().parse(usd);z.number().int().nonnegative().parse(tokens);const q=await pool.query(`UPDATE projects SET data=data || jsonb_build_object('reserved_usd',COALESCE((data->>'reserved_usd')::numeric,0)+$2::numeric,'reserved_tokens',COALESCE((data->>'reserved_tokens')::bigint,0)+$3::bigint),updated_at=now() WHERE id=$1 AND COALESCE((data->>'cost_usd')::numeric,0)+COALESCE((data->>'reserved_usd')::numeric,0)+$2::numeric<=(data->>'budget_cap_usd')::numeric AND (data->>'token_cap' IS NULL OR COALESCE((data->>'tokens_total')::bigint,0)+COALESCE((data->>'reserved_tokens')::bigint,0)+$3::bigint<=(data->>'token_cap')::bigint) RETURNING id`,[projectId,usd,tokens]);return Boolean(q.rowCount); }
 async settleBudget(projectId:string,reservedUsd:number,reservedTokens:number,cost:{tokens_in:number;tokens_out:number;usd:number}):Promise<void> {z.object({tokens_in:z.number().int().nonnegative(),tokens_out:z.number().int().nonnegative(),usd:z.number().nonnegative().finite()}).parse(cost);await pool.query(`UPDATE projects SET data=data || jsonb_build_object('reserved_usd',GREATEST(0,COALESCE((data->>'reserved_usd')::numeric,0)-$2::numeric),'reserved_tokens',GREATEST(0,COALESCE((data->>'reserved_tokens')::bigint,0)-$3::bigint),'cost_usd',COALESCE((data->>'cost_usd')::numeric,0)+$4::numeric,'tokens_total',COALESCE((data->>'tokens_total')::bigint,0)+$5::bigint),updated_at=now() WHERE id=$1`,[projectId,reservedUsd,reservedTokens,cost.usd,cost.tokens_in+cost.tokens_out]); }
}
export const store = new PostgresStore();
export async function audit(type:string,actor:string,payload:Record<string,unknown>,project_id?:string) { await store.emit({id:randomUUID(),ts:new Date().toISOString(),project_id:project_id??'system',type,actor,payload} as OfficeEvent); }
