import nodemailer from 'nodemailer';
import {z} from 'zod';
export const FileSchema=z.object({path:z.string().min(1).max(240).refine(p=>!p.startsWith('/')&&!p.split(/[\\/]/).some(x=>x==='..'||x==='.git')&&!p.includes('\0'),'Unsafe path'),content:z.string().max(2000000)});
const RunSchema=z.object({exit_code:z.number(),stdout:z.string(),stderr:z.string(),files:z.array(FileSchema).optional()});
const DeploySchema=z.object({url:z.string().url(),internal_url:z.string().url(),container_id:z.string(),healthy:z.boolean(),setup_url:z.string().url().optional()});
export class Broker {
 constructor(private url=process.env.RUNNER_URL??'http://runner:4100',private token=process.env.RUNNER_TOKEN??''){}
 async request(path:string,input:unknown,signal?:AbortSignal){const response=await fetch(this.url+path,{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${this.token}`},body:JSON.stringify(input),signal:signal??AbortSignal.timeout(180000)});if(!response.ok)throw new Error(`Sandbox broker ${response.status}: ${(await response.text()).slice(0,2000)}`);return await response.json() as unknown;}
 async run(project_id:string,command:string[],files:z.infer<typeof FileSchema>[]=[],signal?:AbortSignal){z.array(FileSchema).parse(files);const result=RunSchema.parse(await this.request('/run',{project_id,command,files,timeout_ms:120000},signal));if(result.exit_code!==0)throw new Error(`Sandbox command failed (${result.exit_code}): ${result.stderr}\n${result.stdout}`);return result;}
 async deploy(project_id:string,version:string){return DeploySchema.parse(await this.request('/deploy',{project_id,version,target:process.env.DEPLOY_TARGET??'docker-local'}));}
 async rollback(project_id:string,container_id?:string){return this.request('/rollback',{project_id,container_id});}
 async archive(project_id:string){return z.object({path:z.string(),checksum:z.string(),size:z.number()}).parse(await this.request('/archive',{project_id}));}
}
export function complianceCheck(text:string){const blocked=/\b(ransomware|malware|phishing|credential[ -]?steal|steal.{0,20}(password|data)|penipuan|curi.{0,20}(data|password)|eksploitasi anak|doxxing)\b/i.test(text);return {decision:blocked?'NO-GO':'GO',risk_score:blocked?100:15,reason:blocked?'Permintaan berbahaya ditolak. Kami dapat membantu membangun solusi yang aman dan legal.':'Tidak ditemukan indikasi penyalahgunaan pada pemeriksaan deterministik; review privasi dan lisensi tetap wajib.'};}
export function escapeHtml(value:string){return value.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));}
export function deliveryEmail(input:{title:string;live_url:string;portal_url:string;summary:string;features:string[];quality:string;repo_url?:string|null;company?:string}){const company=input.company??process.env.COMPANY_NAME??'AutoDev Office';const subject=`Project "${input.title}" Anda sudah live — ${company}`;const text=`Halo,\n\n${input.summary}\n\nAplikasi: ${input.live_url}\nPortal dan Handover Pack: ${input.portal_url}\nRepository: ${input.repo_url??'Source ZIP tersedia di portal'}\nFitur: ${input.features.join(', ')}\nKualitas: ${input.quality}\nAkses admin: buka tautan setup sekali-pakai melalui portal. Berlaku 15 menit; aktivasi membuat sesi admin pada browser. Jika kedaluwarsa, hubungi operator. Tidak ada kata sandi polos pada email.\nRevisi dan survei melalui portal. Garansi 30 hari; dukungan Senin–Jumat 09:00–17:00 WIB.\n${company} · Data project hanya digunakan untuk delivery.`;const values:Record<string,string>={title:input.title,summary:input.summary,live_url:input.live_url,portal_url:input.portal_url,quality:input.quality,features:input.features.join(', '),company};const custom=process.env.EMAIL_TEMPLATE_DELIVERED;const html=custom?custom.replace(/\{\{(\w+)\}\}/g,(_match,key:string)=>escapeHtml(values[key]??'')):`<!doctype html><html lang="id"><meta name="viewport" content="width=device-width"><body style="background:#0b1020;color:#e6eaf5;font-family:Arial,sans-serif"><main style="max-width:640px;margin:auto;padding:32px"><h1>${escapeHtml(input.title)} sudah live</h1><p>${escapeHtml(input.summary)}</p><p><a style="color:#a5b4fc" href="${escapeHtml(input.live_url)}">Buka Aplikasi Anda</a> · <a style="color:#22d3ee" href="${escapeHtml(input.portal_url)}">Client Portal & Handover Pack</a></p><h2>Fitur terkirim</h2><ul>${input.features.map(f=>`<li>${escapeHtml(f)}</li>`).join('')}</ul><h2>Hasil kualitas</h2><p>${escapeHtml(input.quality)}</p><p>Akses admin: tautan setup sekali-pakai di portal, berlaku 15 menit. Aktifkan sesi admin pada browser; jika kedaluwarsa hubungi operator. Tidak ada password polos.</p><p>Source ZIP, PRD, arsitektur, manuals, OpenAPI, release notes, QA/security dan runbook tersedia di portal.</p><p>Revisi dan survei: portal. Garansi 30 hari. Dukungan Senin–Jumat 09:00–17:00 WIB.</p><footer>${escapeHtml(company)} · Privasi klien terjaga · Email transaksional.</footer></main></body></html>`;return {subject,text,html};}
export async function sendEmail(input:{to:string;subject:string;text:string;html:string;idempotency_key:string}){z.string().email().parse(input.to);const from=process.env.EMAIL_FROM??'AutoDev Office <office@autodev.local>';if(process.env.EMAIL_PROVIDER==='resend'){const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{authorization:`Bearer ${process.env.RESEND_API_KEY??''}`,'content-type':'application/json','Idempotency-Key':input.idempotency_key},body:JSON.stringify({from,to:[input.to],subject:input.subject,text:input.text,html:input.html}),signal:AbortSignal.timeout(30000)});if(!response.ok)throw new Error(`Resend failed ${response.status}`);const data=z.object({id:z.string()}).parse(await response.json());return {provider_msg_id:data.id,status:'sent'};}
 const transport=nodemailer.createTransport({host:process.env.SMTP_HOST??'mailpit',port:Number(process.env.SMTP_PORT??1025),secure:process.env.SMTP_SECURE==='true',...(process.env.SMTP_USER?{auth:{user:process.env.SMTP_USER,pass:process.env.SMTP_PASSWORD}}:{}),connectionTimeout:15000,socketTimeout:30000});const info=await transport.sendMail({from,to:input.to,subject:input.subject,text:input.text,html:input.html,messageId:`<${input.idempotency_key.replace(/[^a-zA-Z0-9_-]/g,'-')}@autodev.local>`});if(!info.accepted.length)throw new Error('SMTP did not accept recipient');return {provider_msg_id:String(info.messageId),status:'sent'};
}
export class ToolRegistry {
 private entries=new Map<string,{schema:z.ZodType;agents:string[];execute:(input:unknown)=>Promise<unknown>;last:number}>();
 register(name:string,schema:z.ZodType,agents:string[],execute:(input:unknown)=>Promise<unknown>){this.entries.set(name,{schema,agents,execute,last:0});}
 async execute(agent:string,name:string,input:unknown){const tool=this.entries.get(name);if(!tool||!tool.agents.includes(agent))throw new Error('Tool permission denied');if(Date.now()-tool.last<100)throw new Error('Tool rate limit');tool.last=Date.now();return tool.execute(tool.schema.parse(input));}
}
